spring:
  application:
    name: kartikey

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true   # (feach गलत था → fetch)
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
